# Generated by Django 4.1.5 on 2023-02-02 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(default='Note content.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(default='New Note.', max_length=100),
        ),
    ]
